package com.debadatta.TrimTime.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@AllArgsConstructor
@NoArgsConstructor
@Component
@Scope("prototype")
@DynamoDBTable(tableName = "Appointments")
public class Appointments {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "appointment_id")
    private String appointment_id;

    @DynamoDBAttribute(attributeName = "barber_id")
    private String barber_id;

    @DynamoDBAttribute(attributeName = "customer_id")
    private String customer_id;

    @DynamoDBAttribute(attributeName = "service_id")
    private String service_id;

    @DynamoDBAttribute(attributeName = "appointment_date")
    private String appointment_date;

    @DynamoDBAttribute(attributeName = "appointment_time")
    private String appointment_time;

    @DynamoDBAttribute(attributeName = "appointment_status")
    private String appointment_status; //booked, rescheduled, cancelled
    
}
