package com.debadatta.TrimTime.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@AllArgsConstructor
@NoArgsConstructor
@Component
@Scope("prototype")
@DynamoDBTable(tableName = "Reviews")
public class Reviews {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "review_id")
    private String review_id;

    @DynamoDBAttribute(attributeName = "barber_id")
    private String barber_id;

    @DynamoDBAttribute(attributeName = "customer_id")
    private String customer_id;

    @DynamoDBAttribute(attributeName = "rating")
    private Integer rating;

    @DynamoDBAttribute(attributeName = "comment")
    private String comment;

    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
}
