package com.debadatta.TrimTime.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@AllArgsConstructor
@NoArgsConstructor
@Component
@Scope("prototype")
@DynamoDBTable(tableName = "Services")

public class Services {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "service_id")
    private String service_id;

    @DynamoDBAttribute(attributeName = "barber_id")
    private String barber_id;

    @DynamoDBAttribute(attributeName = "serviceName")
    private String serviceName;

    @DynamoDBAttribute(attributeName = "price")
    private Integer price;

    @DynamoDBAttribute(attributeName = "comment")
    private String duration;

    
}
